import type { Category, Product, SellerSummary } from "./types";

export const CATEGORIES: Category[] = [
  { id: "1", name: "Monnaies", nameAr: "عملات", nameFr: "Monnaies", slug: "coins", icon: "🪙" },
  { id: "2", name: "Montres Vintage", nameAr: "ساعات قديمة", nameFr: "Montres Vintage", slug: "watches", icon: "⌚" },
  { id: "3", name: "Mobilier", nameAr: "أثاث", nameFr: "Mobilier", slug: "furniture", icon: "🪑" },
  { id: "4", name: "Tapis Marocains", nameAr: "سجاد مغربي", nameFr: "Tapis Marocains", slug: "rugs", icon: "🪮" },
  { id: "5", name: "Bijoux Berbères", nameAr: "مجوهرات أمازيغية", nameFr: "Bijoux Berbères", slug: "jewelry", icon: "💎" },
  { id: "6", name: "Cuivre", nameAr: "نحاس", nameFr: "Cuivre", slug: "copper", icon: "🪹" },
  { id: "7", name: "Laiton", nameAr: "برونز", nameFr: "Laiton", slug: "brass", icon: "🔔" },
  { id: "8", name: "Argent", nameAr: "فضة", nameFr: "Argent", slug: "silver", icon: "🥈" },
  { id: "9", name: "Art Islamique", nameAr: "فن إسلامي", nameFr: "Art Islamique", slug: "islamic-art", icon: "🕌" },
  { id: "10", name: "Peintures", nameAr: "لوحات", nameFr: "Peintures", slug: "paintings", icon: "🖼️" },
  { id: "11", name: "Livres", nameAr: "كتب", nameFr: "Livres", slug: "books", icon: "📚" },
  { id: "12", name: "Manuscrits", nameAr: "مخطوطات", nameFr: "Manuscrits", slug: "manuscripts", icon: "📜" },
  { id: "13", name: "Décorations", nameAr: "ديكور", nameFr: "Décorations", slug: "decorations", icon: "✨" },
  { id: "14", name: "Miroirs", nameAr: "مرايا", nameFr: "Miroirs", slug: "mirrors", icon: "🪞" },
  { id: "15", name: "Portes Anciennes", nameAr: "أبواب قديمة", nameFr: "Portes Anciennes", slug: "doors", icon: "🚪" },
  { id: "16", name: "Poterie", nameAr: "فخار", nameFr: "Poterie", slug: "pottery", icon: "🏺" },
  { id: "17", name: "Céramiques", nameAr: "سيراميك", nameFr: "Céramiques", slug: "ceramics", icon: "🪹" },
  { id: "18", name: "Lanternes", nameAr: "فوانيس", nameFr: "Lanternes", slug: "lanterns", icon: "🪔" },
  { id: "19", name: "Armes", nameAr: "أسلحة", nameFr: "Armes", slug: "weapons", icon: "⚔️" },
  { id: "20", name: "Instruments de Musique", nameAr: "آلات موسيقية", nameFr: "Instruments de Musique", slug: "music", icon: "🎵" },
  { id: "21", name: "Appareils Photo", nameAr: "كاميرات", nameFr: "Appareils Photo", slug: "cameras", icon: "📷" },
  { id: "22", name: "Machines à Écrire", nameAr: "آلات كاتبة", nameFr: "Machines à Écrire", slug: "typewriters", icon: "⌨️" },
  { id: "23", name: "Radio", nameAr: "راديو", nameFr: "Radio", slug: "radio", icon: "📻" },
  { id: "24", name: "Vinyles", nameAr: "اسطوانات", nameFr: "Vinyles", slug: "vinyl", icon: "💿" },
  { id: "25", name: "Militaire", nameAr: "عسكري", nameFr: "Militaire", slug: "military", icon: "🎖️" },
  { id: "26", name: "Timbres", nameAr: "طوابع", nameFr: "Timbres", slug: "stamps", icon: "📮" },
  { id: "27", name: "Jouets", nameAr: "ألعاب", nameFr: "Jouets", slug: "toys", icon: "🧸" },
  { id: "28", name: "Pièces Auto", nameAr: "قطع سيارات", nameFr: "Pièces Auto", slug: "car-parts", icon: "🚗" },
  { id: "29", name: "Autre", nameAr: "أخرى", nameFr: "Autre", slug: "other", icon: "📦" },
];

export const MOROCCAN_CITIES = [
  "Casablanca", "Rabat", "Marrakech", "Fès", "Tanger", "Agadir",
  "Meknès", "Oujda", "Kenitra", "Tétouan", "Safi", "El Jadida",
  "Nador", "Béni Mellal", "Errchida", "Taza", "Essaouira", "Ouarzazate",
  "Larache", "Khénifra", "Settat", "Berrechid", "Mohammedia", "Khouribga",
];

const MOCK_SELLER: SellerSummary = {
  id: "s1",
  name: "Hassan Benali",
  avatar: undefined,
  rating: 4.8,
  reviewCount: 127,
  isVerified: true,
  city: "Marrakech",
  memberSince: "2022-03-15",
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Plateau en Cuivre Ciselé du XVIIIe Siècle",
    description: "Magnifique plateau en cuivre ciselé à la main, origine Fès. Décors géométriques islamiques parfaitement conservés.",
    price: 4500, isNegotiable: true, hasAuction: false,
    category: CATEGORIES[5], condition: "excellent", year: 1780, origin: "Fès, Maroc",
    material: "Cuivre", dimensions: "60cm de diamètre", weight: "3.2 kg",
    location: "Médina de Marrakech", city: "Marrakech",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600"],
    seller: MOCK_SELLER, viewCount: 342, favoriteCount: 48, status: "active",
    shippingAvailable: true, pickupAvailable: true,
    createdAt: "2026-07-20T10:00:00Z", updatedAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "2",
    title: "Tapis Berbère Authentique Azilal",
    description: "Tapis berbère tissé à la main par des artisanes de la région d'Azilal. Motifs traditionnels uniques, couleurs naturelles.",
    price: 8900, isNegotiable: true, hasAuction: false,
    category: CATEGORIES[3], condition: "excellent", year: 1960, origin: "Azilal, Maroc",
    material: "Laine pure", dimensions: "250x180 cm",
    location: "Souk des Tapis", city: "Marrakech",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"],
    seller: MOCK_SELLER, viewCount: 521, favoriteCount: 86, status: "active",
    shippingAvailable: false, pickupAvailable: true,
    createdAt: "2026-07-18T10:00:00Z", updatedAt: "2026-07-18T10:00:00Z",
  },
  {
    id: "3",
    title: "Montre de Gousset Longines 1920",
    description: "Montre de gousset en argent massif, mouvement mécanique Longines révisé. Fonctionnelle et en parfait état.",
    price: 12500, isNegotiable: false, hasAuction: true,
    auctionEndDate: "2026-08-05T18:00:00Z", currentBid: 11000, bidCount: 7,
    category: CATEGORIES[1], condition: "good", year: 1920, origin: "Suisse",
    material: "Argent 925", dimensions: "4.5cm",
    location: "Quartier Habous", city: "Casablanca",
    images: ["https://images.unsplash.com/photo-1509941943102-10c232535736?w=600"],
    seller: { ...MOCK_SELLER, id: "s2", name: "Karim Idrissi", city: "Casablanca" },
    viewCount: 678, favoriteCount: 112, status: "active",
    shippingAvailable: true, pickupAvailable: true,
    createdAt: "2026-07-15T10:00:00Z", updatedAt: "2026-07-25T10:00:00Z",
  },
  {
    id: "4",
    title: "Lanterne Marocaine en Fer Forgé",
    description: "Grande lanterne marocaine artisanale en fer forgé avec verre coloré. Style andalou du XIXe siècle.",
    price: 2200, isNegotiable: true, hasAuction: false,
    category: CATEGORIES[17], condition: "good", year: 1890, origin: "Fès, Maroc",
    material: "Fer forgé, Verre coloré", dimensions: "80cm de hauteur",
    location: "Médina de Fès", city: "Fès",
    images: ["https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=600"],
    seller: { ...MOCK_SELLER, id: "s3", name: "Fatima Zahra", isVerified: false, city: "Fès" },
    viewCount: 195, favoriteCount: 29, status: "active",
    shippingAvailable: true, pickupAvailable: true,
    createdAt: "2026-07-22T10:00:00Z", updatedAt: "2026-07-22T10:00:00Z",
  },
  {
    id: "5",
    title: "Bracelet Berbère en Argent Massif",
    description: "Ancien bracelet berbère en argent massif serti de corail et de pierres semi-précieuses. XIXe siècle.",
    price: 6800, isNegotiable: true, hasAuction: false,
    category: CATEGORIES[4], condition: "excellent", year: 1880, origin: "Souss, Maroc",
    material: "Argent, Corail", dimensions: "7cm de diamètre", weight: "145g",
    location: "Tiznit", city: "Agadir",
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600"],
    seller: MOCK_SELLER, viewCount: 287, favoriteCount: 54, status: "active",
    shippingAvailable: true, pickupAvailable: true,
    createdAt: "2026-07-19T10:00:00Z", updatedAt: "2026-07-19T10:00:00Z",
  },
  {
    id: "6",
    title: "Appareil Photo Leica IIIc 1942",
    description: "Leica IIIc en très bon état de conservation. Boîtier chromé avec objectif Elmar 5cm f/3.5.",
    price: 18000, isNegotiable: false, hasAuction: true,
    auctionEndDate: "2026-08-10T20:00:00Z", currentBid: 16500, bidCount: 12,
    category: CATEGORIES[20], condition: "excellent", year: 1942, origin: "Allemagne",
    material: "Métal chromé", dimensions: "13.5x6.7x3.5 cm",
    location: "Centre-ville", city: "Rabat",
    images: ["https://images.unsplash.com/photo-1495121553079-4c61bcce1894?w=600"],
    seller: { ...MOCK_SELLER, id: "s4", name: "Omar Tazi", city: "Rabat" },
    viewCount: 892, favoriteCount: 167, status: "active",
    shippingAvailable: true, pickupAvailable: true,
    createdAt: "2026-07-10T10:00:00Z", updatedAt: "2026-07-28T10:00:00Z",
  },
];

export const CONDITION_LABELS: Record<string, string> = {
  mint: "Parfait état",
  excellent: "Excellent",
  good: "Bon état",
  fair: "État passable",
  poor: "Mauvais état",
};

export const CONDITION_COLORS: Record<string, string> = {
  mint: "text-emerald-700 bg-emerald-50",
  excellent: "text-blue-700 bg-blue-50",
  good: "text-yellow-700 bg-yellow-50",
  fair: "text-orange-700 bg-orange-50",
  poor: "text-red-700 bg-red-50",
};

export const APP_CONFIG = {
  name: "Antiq Morocco",
  description: "La première marketplace de l'antiquité et du vintage au Maroc",
  currency: "MAD",
  locale: "fr-MA",
  supportEmail: "support@antiqmorocco.ma",
};
